version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:latest 
    restart: always 
    environment:
      POSTGRES_USER: stock
      POSTGRES_PASSWORD: stock
    ports:
      - "5432:5432"
  
  frontend:
    image: ${DOCKER_USERNAME}/RecipeConnect-frontend:latest
    container_name: frontend
    ports:
      - '80:3000'
    restart: always

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'

  backend:
    image: ${DOCKER_USERNAME}/RecipeConnect-backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    restart: always
