version: '3.8'
services:
  backend:
    image: recipeconnect-backend:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: myapp-backend
    ports:
      - "3000:3000"
    restart: always

  frontend:
    image: recipeconnect-frontend:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: myapp-frontend
    ports:
      - "5173:5173"
    restart: always
